AcmeSupport/Accounts/urls.py
from django.urls import path
from Accounts.views import login_view, home, logout_view, create_user, create_ticket,create_department, edit_department,view_all_users,view_departments,delete_department,retrieve_all_tickets, delete_ticket
from django.contrib.auth import views as auth_views
from .views import create_ticket

from . import views
app_name = 'Accounts'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('home/', home, name='home'),
    path('logout/', logout_view, name='logout'),
    path('create-user/', create_user, name='create_user'), 
    path('create-ticket/', create_ticket, name='create_ticket'),
    path('create-department/', create_department, name='create-department'),
    path('edit-department/<int:department_id>/', edit_department, name='edit-department'),
    path('view_all_users/', view_all_users, name='view_all_users'),
    path('view_departments/', views.view_departments, name='view_departments'),
    path('delete_department/<int:department_id>/',delete_department, name='delete_department'),
    path('retrieve_all_tickets/', retrieve_all_tickets, name='retrieve_all_tickets'),
    path('delete-ticket/<int:ticket_id>', delete_ticket, name='delete_ticket'),
    
    # path('ticket_page/', ticket, name='ticket_page'),
]

AcmeSupport/AcmeSupport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.auth.views import LoginView
# from django.urls import handler404
from django.views.defaults import page_not_found


handler404 = 'AcmeSupport.urls.page_not_found_view'
# handler404 = page_not_found_view
handler404 = page_not_found


urlpatterns = [
    # re_path(r'^.*$', page_not_found, name='404')
    path('admin/', admin.site.urls),
    path('',include('Accounts.urls')),
    path('', LoginView.as_view(template_name='login.html'), name='login')
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AcmeSupport/Accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='departments', default=1)
    created_at = models.DateTimeField(default=timezone.now)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """
        Creates and saves a new user with the given email and password.
        """
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Creates and saves a new superuser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    phone_number = models.CharField(null=True, blank=True,unique=True, max_length=10)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, default=None, null=True)
    role = models.CharField(max_length=50, null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

class Ticket(models.Model):
    PRIORITY_CHOICES = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    )
    
    subject = models.CharField(max_length=255)
    body = models.TextField()
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='low')
    ticket_email = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ticket_phone_number = models.IntegerField()
    freshdesk_ticket_id = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.subject} ({self.priority})"

AcmeSupport/Accounts/forms.py




from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser, Ticket



from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Ticket

from .models import Department

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name', 'description']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'phone_number', 'password1', 'password2','role','department')




# class TicketForm(forms.ModelForm):
#     class Meta:
#         model = Ticket
#         fields = ['subject', 'body', 'priority', 'ticket_email', 'ticket_phone_number']
#         widgets = {
#             'subject': forms.TextInput(attrs={'class': 'form-control'}),
#             'body': forms.Textarea(attrs={'class': 'form-control'}),
#             'priority': forms.Select(attrs={'class': 'form-control'}),
#             'ticket_email': forms.EmailInput(attrs={'class': 'form-control'}),
#             'ticket_phone_number': forms.TextInput(attrs={'class': 'form-control'}),
#         }
        
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['ticket_email'].widget.attrs.update({'class': 'form-control'})
#         self.fields['ticket_phone_number'].widget.attrs.update({'class': 'form-control'}
class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['subject', 'body', 'priority', 'ticket_email', 'ticket_phone_number']
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
            'ticket_email': forms.EmailInput(attrs={'class': 'form-control'}),
            'ticket_phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['ticket_email'].widget.attrs.update({'class': 'form-control'})
    #     self.fields['ticket_phone_number'].widget.attrs.update({'class': 'form-control'}) 

AcmeSupport/Accounts/views.py
from .models import CustomUser  # Import the CustomUser model
from .forms import DepartmentForm
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
import requests
from django.conf import settings
from django.db import models
# from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
# from hubspot.crm.contacts import SimplePublicObjectInputForCreate, ApiException
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, get_user_model
from django.http import JsonResponse
# Create your views here.
from django.contrib.auth import authenticate, login, logout


from .models import CustomUser
from django.db.models import Q

from .forms import CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
# import hubspot
from pprint import pprint
# from hubspot.crm.contacts import ApiException
# from hubspot.crm.contacts import SimplePublicObjectInput, SimplePublicObjectInputForCreate, ApiException
from .models import Ticket
from .forms import TicketForm
# from hubspot import HubSpot

from .models import Department
from hubspot.crm.tickets import SimplePublicObjectInputForCreate, ApiException
import requests
from django.shortcuts import render, get_object_or_404, redirect

from django.shortcuts import render
from .models import Ticket







import json

from django.views.decorators.csrf import csrf_exempt
from .models import Ticket

import requests
from django.http import JsonResponse

def authenticate(request, email_or_phone_number=None, password=None):
    # UserModel = get_user_model()
    if email_or_phone_number is None or password is None:
        return None
    try:
        user = CustomUser.objects.get(
            Q(email=email_or_phone_number) | Q(phone_number=email_or_phone_number))
        if user.check_password(password):
            return user
    except CustomUser.DoesNotExist:
        return None


@csrf_exempt
def login_view(request):
    if request.method == 'POST':
        email_or_phone_number = request.POST.get('email_or_phone_number')
        password = request.POST.get('password')

        user = authenticate(
            request, email_or_phone_number=email_or_phone_number, password=password)
        if user is not None:
            # The user's credentials are correct, so log them in
            login(request, user)
            # if user.is_superuser:
            #     # If the user is an admin, redirect to the ticket page
            #     return redirect('ticket_page')
            # else:
            # If the user is a regular user, redirect to the home page
            return redirect('Accounts:home')
        else:
            # The user's credentials are incorrect, so return an error message
            return JsonResponse({'success': False, 'message': 'Invalid login credentials'})
    else:
        return render(request, 'login.html')


@login_required(login_url='login')
def home(request):
    if request.user.is_authenticated:
        user = request.user  # Get the logged-in user
    # Filter tickets based on the logged-in user
    tickets = Ticket.objects.filter(ticket_email=user)
    context = {'tickets': tickets}
    return render(request, 'home.html', context)


@login_required(login_url='Accounts:login')
def logout_view(request):
    logout(request)
    return redirect('Accounts:login')





def admin_required(function):
    def wrap(request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('home')  # Redirect to home page if not an admin
        return function(request, *args, **kwargs)
    return wrap


# Redirects non-admin users to home page
@staff_member_required(login_url='Accounts:home')
# Redirects non-logged-in users to login page
@login_required(login_url='Accounts:login')
def create_department(request):
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            department = form.save(commit=False)
            department.created_by = request.user
            department.save()
            # Replace with your department list URL
            return redirect('Accounts:home')
    else:
        form = DepartmentForm()
    return render(request, 'department_create.html', {'form': form})


# Redirects non-admin users to home page
@staff_member_required(login_url='home')
# Redirects non-logged-in users to login page
@login_required(login_url='login')
def edit_department(request, department_id):
    department = get_object_or_404(Department, id=department_id)

    if request.method == 'POST':
        form = DepartmentForm(request.POST, instance=department)
        if form.is_valid():
            form.save()
            return redirect('home')  # Replace with your department list URL
    else:
        form = DepartmentForm(instance=department)

    return render(request, 'department_edit.html', {'form': form, 'department': department})


@login_required
# Redirects non-admin users to home page
@staff_member_required(login_url='Accounts:home')
@login_required(login_url='Accounts:login')
def delete_department(request, department_id):
    department = get_object_or_404(Department, id=department_id)

    # Check if the current user is an admin
    if not request.user.is_superuser:
        return JsonResponse({'error': 'Only admin users can delete departments.'}, status=403)

    # Check if the department is assigned to any user
    if CustomUser.objects.filter(department=department).exists():
        return JsonResponse({'error': 'The department is assigned to one or more users and cannot be deleted.'}, status=400)

    # Delete the department
    department.delete()
    return JsonResponse({'message': 'Department deleted successfully.'})


# Redirects non-admin users to home page
@staff_member_required(login_url='Accounts:home')
@login_required(login_url='Accounts:login')
def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            role = form.cleaned_data['role']
            department = form.cleaned_data['department']

            # Create contact in HubSpot

            # Check if contact already exists in Django model
            if CustomUser.objects.filter(email=email).exists() or CustomUser.objects.filter(phone_number=phone_number).exists():
                pprint("Contact already exists in Django model.")
            else:
                # Save contact to Django model
                try:
                    user = CustomUser(
                        email=email,
                        phone_number=phone_number,
                        department=department,  # Set the department accordingly if available
                        role=role,  # Set the role accordingly if available
                        created_by=None,  # Set the created_by accordingly if available
                        is_active=True,  # Set the active status accordingly if available
                        is_staff=False,  # Set the staff status accordingly if available
                    )
                    user.set_password(password1)
                    user.save()
                    return redirect('home')
                except Exception as e:
                    # Handle the error if the contact already exists in Django model
                    pprint(f"Error saving contact to Django model: {e}")

    else:
        form = CustomUserCreationForm()

    return render(request, 'create-user.html', {'form': form})


@staff_member_required(login_url='Accounts:home')
@login_required(login_url='Accounts:home')
def view_all_users(request):
    if not request.user.is_staff:
        return redirect('Accounts:home')

    users = CustomUser.objects.all()
    return render(request, 'users.html', {'users': users})


@login_required
@user_passes_test(lambda u: u.is_staff, login_url='Accounts:home')
def view_departments(request):
    departments = Department.objects.all()
    return render(request, 'departments.html', {'departments': departments})


PRIORITY_MAPPING = {
    'low': 1,
    'medium': 2,
    'high': 3,
}



@csrf_exempt
# def create_ticket(request):
#     if request.method == 'POST':
#         # Extract the data from the request
#         subject = request.POST.get('subject')
#         body = request.POST.get('body')
#         priority = request.POST.get('priority')
#         ticket_email = request.POST.get('ticket_email')
#         ticket_phone_number = request.POST.get('ticket_phone_number')

#         # Map priority value to numeric value
#         priority_mapping = {
#             'low': 1,
#             'medium': 2,
#             'high': 3,
#         }
#         # Default to 1 if priority is not found
#         priority = priority_mapping.get(priority, 1)

#         # Create the ticket in Freshdesk
#         url = 'https://acme8306.freshdesk.com/api/v2/tickets'
#         headers = {'Content-Type': 'application/json'}
#         auth = ('1DTPsoWBTnqpLENEEWf', 'X')
#         data = {
#             'description': body,
#             'subject': subject,

AcmeSupport/Accounts/templates/create-ticket.html
<!-- <!DOCTYPE html>
<html>
<head>
    <title>Create Ticket</title>
    <style>
        .form-group {
            margin-bottom: 10px;
        }
        label {
            display: block;
            font-weight: bold;
        }
        input[type="text"],
        textarea,
        select {
            width: 100%;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        button[type="submit"] {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <h1>Create Ticket</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="form-group">
            <label for="id_body">Body:</label>
            {{ form.body }}
        </div>
        <div class="form-group">
            <label for="id_priority">Priority:</label>
            {{ form.priority }}
        </div>
        <div class="form-group">
            <label for="id_ticket_email">Ticket Email:</label>
            <input
            type="text"
            class="w-full p-2 border border-grey-300 rounded-md placeholder:font-light placeholder:text-grey-500 active:border-sky-400"
            name="ticket_email"
            id="id_ticket_email"
            id="email_or_phone_number"
            value="{{ request.user.email }}"
            disabled
        >
        </div>
        <div class="form-group">
            <label for="id_ticket_phone_number">Ticket Phone Number:</label>
            <input
            
            type="text"
            name="ticket_phone_number"
            id="id_ticket_phone_number"
            value="{{ request.user.phone_number }}"
            class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light placeholder:text-gray-500"
        >
        </div>
        <button type="submit">Submit</button>
    </form>
</body>
</html> -->
<!-- <form method="post">
    {% csrf_token %}
    
    <div>
        <label for="{{ form.subject.id_for_label }}">Subject:</label>
        {{ form.subject }}
    </div>
    
    <div>
        <label for="{{ form.body.id_for_label }}">Body:</label>
        {{ form.body }}
    </div>
    
    <div>
        <label for="{{ form.priority.id_for_label }}">Priority:</label>
        {{ form.priority }}
    </div>
    
    <div>
        <label for="{{ form.ticket_email.id_for_label }}">Ticket Email:</label>
        <input type="email" name="ticket_email" class="form-control" required id="id_ticket_email" value="{{ request.user.email }}">
    </div>
    
    <div>
        <label for="{{ form.ticket_phone_number.id_for_label }}">Ticket Phone Number:</label>
        <input type="text" name="ticket_phone_number" class="form-control" required id="id_ticket_phone_number" value="{{ request.user.phone_number }}">
    </div>
    
    <button type="submit">Submit</button>
</form> -->
<!-- <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create ticket">
</form> -->
<!-- create_ticket.html -->
<form method="post" action="{% url 'Accounts:create_ticket' %}">
    {% csrf_token %}
    <label for="subject">Subject:</label>
    <input type="text" name="subject" required>
    <br>
    <label for="body">Body:</label>
    <textarea name="body" required></textarea>
    <br>
    <label for="priority">Priority:</label>
    <select name="priority">
        <option value="low">Low</option>
        <option value="medium">Medium</option>
        <option value="high">High</option>
    </select>
    <br>
    <label for="ticket_email">Email:</label>
    <input type="email" name="ticket_email" required value="{{request.user.email}}">
    <br>
    <label for="ticket_phone_number">Phone Number:</label>
    <input type="tel" name="ticket_phone_number" required value="{{request.user.phone_number}}">
    <br>
    <input type="submit" value="Submit">
</form>

AcmeSupport/Accounts/templates/departments.html
{% extends 'base.html' %}



{% block content %}
{% if user.is_authenticated and user.is_staff %}
<div class="p-5 h-screen bg-gray-100">
    <h1 class="flex">

        <h1 class="text-xl mb-2">Departments</h1>
        <button
        class="bg-[#38bdf8] text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black hover:border hover:border-gray-300"
        
        
      >
      <a href="{% url 'Accounts:create-department' %}">Add Department</a>
       
      </button>
    </h1>
 
    <div class="overflow-auto rounded-lg shadow hidden md:block">
      <table class="w-full">
        <thead class="bg-gray-50 border-b-2 border-gray-200">
        <tr>
            <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Department_Name</th>
          <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Created_BY</th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">Created_at</th>
          <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Edit</th>
          <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">Delete</th>
          <!-- <th class="w-32 p-3 text-sm font-semibold tracking-wide text-left">password</th> -->
        </tr>
        </thead>
        <tbody class="divide-y divide-gray-100">
            {% for department in departments %}
        <tr class="bg-white">
            <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
                <a href="#" class="font-bold text-blue-500 hover:underline">{{ department.name }}</a>
              </td>
          <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
            <a href="#" class="font-bold text-blue-500 hover:underline">{{ department.created_by }}</a>
          </td>
          <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
           {{ department.created_at  }}
          </td>
          <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
          <span
            class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50"><a href="{% url 'Accounts:edit-department' department.id %}">Edit</a></span>
          </td>
          <td class="p-3 text-sm text-gray-700 whitespace-nowrap"><a class="delete-button" data-department-id="{{ department.id }}">Delete</a></td>
         
        </tr>
        {% endfor %}
       
       
    </tbody>
</table>
</div>
 

</div>
{% else %}
<p>You are not authorized to view this page. Redirecting to the home page...</p>
<script>
    setTimeout(function() {
      window.location.href = "{% url 'home' %}";
    }, 3000);  // Redirect after 3 seconds
  </script>
{% endif %}
<!-- Add this inside your department_list.html template -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  // Function to handle the delete department request
  function deleteDepartment(departmentId) {
    $.ajax({
      url: `/delete_department/${departmentId}/`,
      type: 'DELETE',
      beforeSend: function(xhr) {
        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
      },
      success: function() {
        alert('Department deleted successfully');
        window.location.reload(); // Refresh the page after successful deletion
      },
      error: function() {
        alert('An error occurred while deleting the department');
      }
    });
  }

  // Event listener for the delete button
  $('.delete-button').click(function() {
    var departmentId = $(this).data('department-id');
    if (confirm('Are you sure you want to delete this department?')) {
      deleteDepartment(departmentId);
    }
  });
});
</script>

{% endblock content %}
    

AcmeSupport/Accounts/templates/home.html
{% extends 'base.html' %}



{% block content %}
{% if user.is_authenticated %}
<div class="p-5 h-screen bg-gray-100">
  <div class="flex">

    <h1 class="text-xl mb-2">My Tickets</h1>
    <button
    class="bg-[#38bdf8] text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black hover:border hover:border-gray-300"
    
    
  >
  <a href="{% url 'Accounts:create_ticket' %}">ADD Ticket</a>
   
  </button>
  </div>
 
 {% if tickets %}
  
 
   <div class="overflow-auto rounded-lg shadow hidden md:block">
     <table class="w-full">
       <thead class="bg-gray-50 border-b-2 border-gray-200">
       <tr>
           <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">ID</th>
           <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Subject</th>
         <th class="w-20 p-3 text-sm font-semibold tracking-wide text-left">Priority</th>
         <th class="w-24 p-3 text-sm font-semibold tracking-wide text-left">body</th>
         <th class="p-3 text-sm font-semibold tracking-wide text-left">Created_at</th>
         <!-- <th class="w-32 p-3 text-sm font-semibold tracking-wide text-left">password</th> -->
       </tr>
       </thead>
       <tbody class="divide-y divide-gray-100">
           {% for ticket in tickets %}
       <tr class="bg-white">
           <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
               <a href="#" class="font-bold text-blue-500 hover:underline">{{ ticket.id }}</a>
             </td>
         <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
           <a href="#" class="font-bold text-blue-500 hover:underline">{{ ticket.subject }}</a>
         </td>
         <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
          {{ ticket.priority }}
         </td>
         <td class="p-3 text-sm text-gray-700 whitespace-nowrap">
         <span
           class="p-1.5 text-xs font-medium uppercase tracking-wider text-green-800 bg-green-200 rounded-lg bg-opacity-50">{{ticket.body}}</span>
         </td>
         <td class="p-3 text-sm text-gray-700 whitespace-nowrap">{{ ticket.created_at }}</td>
        
       </tr>
       {% endfor %}
      
      
   </tbody>
</table>
</div>
{% else %}
<h1 class="text-2xl font-bold mb-4">No tickets</h1>
 {% endif %}
 

</div>
{% else %}
<!-- <p>You are not authorized to view this page. Redirecting to the home page...</p> -->
<script>
    setTimeout(function() {
      window.location.href = "{% url 'Accounts:home' %}";
    }, 3000);  // Redirect after 3 seconds
  </script>
{% endif %}
{% endblock content %}

AcmeSupport/Accounts/templates/navbar.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </head>
    <body class="">
        <nav class="p-5 bg-white shadow md:flex md:items-center md:justify-between">
            <div class="flex justify-between items-center ">
                <span class="text-2xl font-[Poppins] cursor-pointer">
                    <img class="h-10 inline" src="https://tailwindcss.com/_next/static/media/social-square.b622e290e82093c36cca57092ffe494f.jpg">
                    tailwind
                </span>
                <span class="text-3xl cursor-pointer mx-2 md:hidden block">
                    <ion-icon name="menu" onclick="Menu(this)"></ion-icon>
                </span>
            </div>
            <ul class="md:flex md:items-center z-[-1] md:z-auto md:static absolute bg-white w-full left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-7 md:opacity-100 opacity-0 top-[-400px] transition-all ease-in duration-500">
                {% if request.user.is_authenticated %}
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'Accounts:home' %}" class="text-xl hover:text-cyan-500 duration-500">Home</a>
                </li>
                {% endif %}
        {% if request.user.is_authenticated %}
        {% if request.user.is_superuser %}
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'Accounts:view_departments' %}" class="text-xl hover:text-cyan-500 duration-500">Department</a>
                </li>
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'Accounts:view_all_users' %}" class="text-xl hover:text-cyan-500 duration-500">Users</a>
                </li>
                {% endif %}
            {% endif %}
         
          
            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'Accounts:retrieve_all_tickets' %}" class="text-xl hover:text-cyan-500 duration-500">User Ticket</a>
                </li>
                {% endif %}
            {% endif %}
         
            {% if request.user.is_authenticated %}
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'Accounts:logout' %}" class="text-xl hover:text-cyan-500 duration-500">Logout</a>
                </li>
                {% endif %}
            </ul>
            <h2 class=""></h2>
        </ul>
    </nav>
    <script>
    function Menu(e){
      let list = document.querySelector('ul');
      e.name === 'menu' ? (e.name = "close",list.classList.add('top-[80px]') , list.classList.add('opacity-100')) :( e.name = "menu" ,list.classList.remove('top-[80px]'),list.classList.remove('opacity-100'))
    }
    </script>
</body>
</html>